### ISSUE TITLE
Programming model v4: ApplicationInsights:Failed to propagate context in Azure Functions

### ISSUE THREAD

**Issue by mfontes** [Azure/azure-functions-nodejs-library#110]
#### Investigative information

Please provide the following:

- Timestamp: 2023-07-13T20:50:15.107Z
- Invocation ID: e06a80f2-9b01-4cd7-abb3-36486ab30de7
- Region: Locally running Function host

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a basic timer function
2. Import applicationinsights (v2.7.0)
3. Begin automatic collection with `appinsights.setup().start()`
4. Execute the function

See Source section at the end for sample code

#### Expected behavior

Application insights Auto Collection begins successfully

#### Actual behavior

An error is logged:
```
ApplicationInsights:Failed to propagate context in Azure Functions [
   TypeError: Cannot read properties of undefined (reading 'find')
       at AzureFunctionsHook._isHttpTrigger (<function root>/node_modules/applicationinsights/out/AutoCollection/AzureFunctionsHook.js:190:39)
       at AzureFunctionsHook.<anonymous> (<function root>/node_modules/applicationinsights/out/AutoCollection/AzureFunctionsHook.js:94:38)
       at step (<function root>/node_modules/applicationinsights/out/AutoCollection/AzureFunctionsHook.js:33:23)
       at Object.next (<function root>/node_modules/applicationinsights/out/AutoCollection/AzureFunctionsHook.js:14:53)
       at <function root>/node_modules/applicationinsights/out/AutoCollection/AzureFunctionsHook.js:8:71
       at new Promise (<anonymous>)
       at __awaiter (<function root>/node_modules/applicationinsights/out/AutoCollection/AzureFunctionsHook.js:4:12)
       at <function root>/node_modules/applicationinsights/out/AutoCollection/AzureFunctionsHook.js:78:136
       at t.WorkerChannel.<anonymous> (/usr/local/Cellar/azure-functions-core-tools@4/4.0.5085/workers/node/dist/src/worker-bundle.js:2:16100)
       at Generator.next (<anonymous>)
  ]
```
#### Known workarounds

Unknown

#### Related information 

This issue may be better directed at towards applicationinsights, but I thought I'd try here first since I am using the public preview version of this library.

* Programming language used - NodeJS 18.15.0
* @azure/functions: "^4.0.0-alpha.10"
* applicationinsights: "^2.7.0"

<details>
<summary>Source</summary>

```node
import { app } from '@azure/functions';
import ai from 'applicationinsights';

ai.setup().start();

async function myTimerFunction (_, context) {}

app.timer('myTimerFunction', {
  schedule: '*/15 * * * * *',
  handler: myTimerFunction,
});
```
</details>

**Comment by ejizba** [comment]
Hi @mfontes for now this scenario isn't supported. We're working on adding support (with collaboration from the app insights team), although I don't think we have a GitHub issue tracking the fix yet. Thanks for filing!

**Comment by ejizba** [comment]
PR was merged. Will be included in the next release of `applicationinsights` npm package

**Comment by ejizba** [comment]
Fyi, applicationinsights v2.8.0 was just released
