### ISSUE TITLE
Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by GravlLift** [Azure/azure-functions-nodejs-library#210]
#### Investigative information

Please provide the following:

- Timestamp: 2024-01-22T22:14:28.4980344Z
- Function App name: AZUD-RMS-FA-01
- Function name(s) (as appropriate): customerLookup
- Invocation ID: 3325acd5-1aad-4923-bffc-0a6fbfe52204
- Region: East US 2

#### Repro steps

Provide the steps required to reproduce the problem:

1. Open `https://azud-rms-fa-01.azurewebsites.net/api/v4/customer?emailAddress=lightspeed.e2e%40gmail.com` in a browser

#### Expected behavior

Provide a description of the expected behavior.

Http request should return valid JSON and 200 response

#### Actual behavior

500 error

#### Related information 

Provide any related information 

* Programming language used: javascript
* Bindings used:

```ts
app.get("customerLookup", {
  authLevel: "anonymous",
  route: `api/v{version:int:min(4):max(${currentMajorVersion})}/customer`,
  handler,
});
```

* Stack Trace:
```
Stack: TypeError: Cannot read properties of undefined (reading 'type')
    at InvocationModel.<anonymous> (/node_modules/@azure/functions/dist/webpack:/@azure/functions/src/InvocationModel.ts:65:63)
    at Generator.next (<anonymous>)
    at <anonymous> (/node_modules/@azure/functions/dist/webpack:/@azure/functions/src/InvocationContext.ts:96:10)
    at new Promise (<anonymous>)
    at __webpack_modules__../src/InvocationModel.ts.__awaiter (/node_modules/@azure/functions/dist/webpack:/@azure/functions/src/InvocationContext.ts:96:10)
    at InvocationModel.getArguments (/node_modules/@azure/functions/dist/webpack:/@azure/functions/src/InvocationModel.ts:46:23)
    at y.<anonymous> (/azure-functions-host/workers/node/dist/src/worker-bundle.js:2:37611)
    at Generator.next (<anonymous>)
    at o (/azure-functions-host/workers/node/dist/src/worker-bundle.js:2:35629)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

This error is not reproducible locally, only on our Azure instance. While it is reproducible for a single function run, restarting the function will fix the issue.

Relevant code appears to be here:

https://github.com/Azure/azure-functions-nodejs-library/blob/aa9068df56c2d4c2b90ee55dd42005e1d7c5cb4c/src/InvocationModel.ts#L46-L79

**Comment by ejizba** [comment]
Hi @GravlLift I'm not sure what could be causing this, but my best guess is it's some sort of race condition that only happens with more complex projects. It'll be hard for me to repro, so it would be helpful if we could get more logs. Could you replace line 203 in `node_modules/@azure/functions/dist/azure-functions.js` which should look like this:
```typescript
const bindingType = __classPrivateFieldGet(this, _InvocationModel_bindings, "f")[bindingName].type;
```

With this code:
```typescript
let bindingType;
try {
    bindingType = __classPrivateFieldGet(this, _InvocationModel_bindings, "f")[bindingName].type;
} catch (err) {
    context.log(`bindingName: ${bindingName}`);
    context.log(`inputData: ${JSON.stringify(req.inputData.map((id) => id.name))}`);
    context.log(`bindings: ${JSON.stringify(__classPrivateFieldGet(this, _InvocationModel_bindings, "f"))}`);
    throw err;
}
```

And then share the new logs with us if/when you get the error to reproduce again.

**Comment by sga-solita** [comment]
We are getting this error as well, in a timer triggered function:
```
Exception while executing function: Functions.NameOfTimerTrigger Result: Failure
Exception: Cannot read properties of undefined (reading 'type')
Stack: TypeError: Cannot read properties of undefined (reading 'type')
    at InvocationModel.<anonymous> (/home/site/wwwroot/node_modules/@azure/functions/dist/azure-functions.js:203:114)
    at Generator.next (<anonymous>)
    at /home/site/wwwroot/node_modules/@azure/functions/dist/azure-functions.js:142:71
    at new Promise (<anonymous>)
    at __webpack_modules__../src/InvocationModel.ts.__awaiter (/home/site/wwwroot/node_modules/@azure/functions/dist/azure-functions.js:138:12)
    at InvocationModel.getArguments (/home/site/wwwroot/node_modules/@azure/functions/dist/azure-functions.js:187:16)
    at y.<anonymous> (/azure-functions-host/workers/node/dist/src/worker-bundle.js:2:37611)
    at Generator.next (<anonymous>)
    at o (/azure-functions-host/workers/node/dist/src/worker-bundle.js:2:35629)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

When I look in the logs, it seems to start happening at midnight, and then a restart resolves it. Then next midnight it starts happening again. Although that could be because we have multiple other functions starting at that time, but Im not sure.

**Comment by GravlLift** [comment]
@ejizba, took a while for it to reappear, but here it is:

```
bindingName: httpTrigger17
inputData: ["httpTrigger17"]
bindings: {"httpTrigger19":{"authLevel":"anonymous","route":"api/v3/shipments","methods":["GET"],"type":"httpTrigger","name":"httpTrigger19","direction":"in"},"$return":{"type":"http","name":"httpOutput19","direction":"out"}}
```

The route seen under bindings is the one that crashed when this was logged.

**Comment by ejizba** [comment]
@GravlLift thanks for the info! I just merged a change that I'm pretty confident will fix this, although it's hard to reproduce the bug so I can't be 100% sure. The change will be included in the next release towards the end of February, although you can try it out earlier following these instructions: https://github.com/Azure/azure-functions-nodejs-library/wiki/Install-Insiders-Build

If you do try it out, let us know if it works or not! Thanks
